const GET_TODOS = "GET_TODOS";
const GET_TODO_DETAIL = "GET_TODO_DETAIL";
const DELETE_TODO = "DELETE_TODO";
const CREATE_TODO = "CREATE_TODO";
const UPDATE_TODO = "UPDATE_TODO";
const GET_TODO_DATA_TO_UPDATE = "GET_TODO_DATA_TO_UPDATE";
const LOGIN = "LOGIN";
const LOGIN_LOADING = "LOGIN_LOADING";
const REGISTER = "REGISTER";
const REGISTER_LOADING = "REGISTER_LOADING";
const SET_IS_FETCHING_TODOS = "SET_IS_FETCHING_TODOS";


export {
  SET_IS_FETCHING_TODOS,
  GET_TODOS,
  GET_TODO_DETAIL,
  DELETE_TODO,
  UPDATE_TODO,
  CREATE_TODO,
  GET_TODO_DATA_TO_UPDATE,
  LOGIN,
  LOGIN_LOADING,
  REGISTER,
  REGISTER_LOADING
};